# Generated by Django 3.0.4 on 2020-03-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='name',
            new_name='subject',
        ),
    ]
